Turn anatole theme into a hugo module
lxndrblz/anatole pull request #291
Opened 2022-01-07 20:55 UTC by deining

This PR turns the theme into a hugo module.
With `git`and `go` installed, making use of the anatole theme is now as easy as:

```
hugo new site my_site
cd mysite
echo 'theme = "github.com/lxndrblz/anatole"' >> config.toml
hugo server
```

Copying/cloning the theme in the themes folder is still possible of course.

If desired, I can extend the `Quickstart` section in `README.md`, explaining how to make use of the theme as module.

2022-01-07 21:44 UTC, lxndrblz commented
@deining Thanks for the PR. 

Would you mind adding a brief explanation to the QuickStart section of the Readme?

2022-01-08 20:10 UTC, deining commented
> Would you mind adding a brief explanation to the QuickStart section of the Readme?

I just added a commit that adds documentation on how to use the theme as module.
Please let me know if you like it. I proposed using modules as recommended approach, but I'm certainly biased here.

2022-01-12 12:49 UTC, lxndrblz requested changes
@deining Thanks so much for your PR. Everything works as expected and it is good to have an alternative approach in addition to the current way of adding the theme.

Personally, I am a bit torn, whether we should add the new way really as Route 1 in the readme, as most users might not have go installed but simply rely on the executable for creating and building the site. Therefore, I would probably flip route 1 and 2 as this still seems to be the prevalent approach in the community. What do you think?

2022-01-12 13:29 UTC, deining commented
> @deining Thanks so much for your PR. Everything works as expected and it is good to have an alternative approach in addition to the current way of adding the theme.

Glad to hear that.

> Personally, I am a bit torn, whether we should add the new way really as Route 1 in the readme, as most users might not have go installed but simply rely on the executable for creating and building the site. Therefore, I would probably flip route 1 and 2 as this still seems to be the prevalent approach in the community. What do you think?

I intentionally put the hugo approach in first place. Having worked with modules for a while now, I think they are superior to git submodules. Admittedly, the difference is not that big, handling themes the traditional way is certainly a reasonable approach. You may read this [blog post](https://chrisshort.net/from-git-submodule-to-hugo-modules-using-netlify/), I fully agree with what is stated there. Also, I see that hugo maintainers clearly go for the module approach (see [Ananke theme](https://github.com/theNewDynamic/gohugo-theme-ananke), [DocuApi theme](https://github.com/bep/docuapi), ...). Please also note that official hugo docs dropped section on [Installing and using themes](https://gohugobrasil.netlify.app/themes/installing-and-using-themes/) in favour of a section on  [Hugo modules](https://gohugo.io/hugo-modules/). And yes, your are certainly right, route 2 is currently the prevalent approach in the community. So it's up to you if you want to go mainstream or be innovative 😉 .

@lxndrblz, you are the maintainer of this theme, it's completely your decision. If you decide to flip route 1 and route 2, we will do that. Let me know what you flip route 1 and route 2 and if so, if you want me to do it or do it by yourself. In any case, in `go.mod`, we should set minimum go version to `1.12` (it's `1.17` right now).

Thanks for reviewing and accepting my PR (with whatever route order, it's up to you).

2022-01-12 19:46 UTC, lxndrblz commented
@deining Thanks for the links. After reading through and reviewing them, I agree that the go based approach should be the preferred way forward.

2022-01-12 20:51 UTC, deining commented
> @deining Thanks for the links. After reading through and reviewing them, I agree that the go based approach should be the preferred way forward.

Great!

I set the minimum version in both `go.mod` files to 1.12. Any further issues that should be adressed? From my point of view, my PR is ready for merging now.

2022-01-14 11:02 UTC, lxndrblz approved these changes
@deining LGTM. Thanks for the PR!

2022-01-14 11:11 UTC, merged